# Generated by Django 5.2.7 on 2025-11-01 22:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='M_UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp automático de creación', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp automático de última modificación', verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo', verbose_name='Activo')),
                ('bio', models.TextField(blank=True, help_text='Descripción corta del usuario', max_length=500, null=True, verbose_name='Biografía')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Foto de perfil')),
                ('total_points', models.IntegerField(default=0, help_text='Puntos acumulados por acciones sostenibles', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Puntos totales')),
                ('level', models.IntegerField(default=1, help_text='Nivel del usuario en la app', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nivel')),
                ('total_co2_saved', models.FloatField(default=0.0, help_text='Total de CO2 ahorrado en kg', validators=[django.core.validators.MinValueValidator(0)], verbose_name='CO2 Total Ahorrado')),
                ('streak_days', models.IntegerField(default=0, help_text='Días consecutivos registrando actividades', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Racha de días')),
                ('last_activity_date', models.DateField(blank=True, null=True, verbose_name='Última actividad')),
                ('daily_co2_goal', models.FloatField(default=8.0, help_text='Objetivo diario de emisiones en kg CO2', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Objetivo diario CO2')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Notificaciones habilitadas')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
                'ordering': ['-total_points'],
            },
        ),
    ]
