# Generated by Django 5.2.7 on 2025-11-01 22:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='M_Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp automático de creación', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp automático de última modificación', verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo', verbose_name='Activo')),
                ('transport_type', models.CharField(choices=[('car', 'Auto'), ('electric_car', 'Auto eléctrico'), ('bus', 'Autobús'), ('metro', 'Metro'), ('train', 'Tren'), ('motorcycle', 'Motocicleta'), ('bike', 'Bicicleta'), ('walk', 'Caminar'), ('scooter', 'Scooter eléctrico'), ('plane', 'Avión')], max_length=20, verbose_name='Tipo de transporte')),
                ('distance_km', models.FloatField(help_text='Distancia recorrida en kilómetros', validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Distancia (km)')),
                ('origin', models.CharField(blank=True, max_length=255, verbose_name='Origen')),
                ('destination', models.CharField(blank=True, max_length=255, verbose_name='Destino')),
                ('total_co2', models.FloatField(help_text='Emisiones totales calculadas en kg de CO2', validators=[django.core.validators.MinValueValidator(0)], verbose_name='CO2 Total (kg)')),
                ('trip_date', models.DateField(verbose_name='Fecha del viaje')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Transporte',
                'verbose_name_plural': 'Transportes',
                'ordering': ['-trip_date', '-created_at'],
                'indexes': [models.Index(fields=['user', '-trip_date'], name='transport_m_user_id_0934e0_idx')],
            },
        ),
    ]
