# Generated by Django 5.2.7 on 2025-11-02 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp automático de creación', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp automático de última modificación', verbose_name='Última actualización')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('icon', models.CharField(default='🏆', max_length=10, verbose_name='Ícono')),
                ('category', models.CharField(choices=[('meals', 'Comidas'), ('transport', 'Transporte'), ('energy', 'Energía'), ('social', 'Social'), ('general', 'General')], max_length=20, verbose_name='Categoría')),
                ('requirement_type', models.CharField(choices=[('meal_count', 'Cantidad de comidas'), ('vegan_meal_count', 'Comidas veganas'), ('vegetarian_meal_count', 'Comidas vegetarianas'), ('transport_count', 'Cantidad de viajes'), ('eco_transport_count', 'Transporte ecológico'), ('co2_saved', 'CO2 ahorrado total'), ('daily_streak', 'Días consecutivos'), ('friend_count', 'Cantidad de amigos'), ('level_reached', 'Nivel alcanzado')], max_length=30, verbose_name='Tipo de Requisito')),
                ('requirement_value', models.IntegerField(verbose_name='Valor Requerido')),
                ('points', models.IntegerField(default=100, verbose_name='Puntos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Logro',
                'verbose_name_plural': 'Logros',
                'db_table': 'achievements',
                'ordering': ['category', 'requirement_value'],
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp automático de creación', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp automático de última modificación', verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo', verbose_name='Activo')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada')], default='pending', max_length=10, verbose_name='Estado')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Aceptada el')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_sent', to=settings.AUTH_USER_MODEL, verbose_name='De Usuario')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_received', to=settings.AUTH_USER_MODEL, verbose_name='Para Usuario')),
            ],
            options={
                'verbose_name': 'Amistad',
                'verbose_name_plural': 'Amistades',
                'db_table': 'friendships',
                'ordering': ['-created_at'],
                'unique_together': {('from_user', 'to_user')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp automático de creación', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp automático de última modificación', verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo', verbose_name='Activo')),
                ('unlocked_at', models.DateTimeField(blank=True, null=True, verbose_name='Desbloqueado el')),
                ('progress', models.IntegerField(default=0, verbose_name='Progreso (%)')),
                ('is_unlocked', models.BooleanField(default=False, verbose_name='Desbloqueado')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_by', to='social.achievement', verbose_name='Logro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Logro de Usuario',
                'verbose_name_plural': 'Logros de Usuarios',
                'db_table': 'user_achievements',
                'ordering': ['-unlocked_at', '-created_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
