# Generated by Django 5.2.7 on 2025-11-02 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='icon',
        ),
    ]
