# Generated by Django 5.2.7 on 2025-11-01 22:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='M_Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp automático de creación', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp automático de última modificación', verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo', verbose_name='Activo')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Desayuno'), ('lunch', 'Almuerzo'), ('dinner', 'Cena'), ('snack', 'Snack')], max_length=20, verbose_name='Tipo de comida')),
                ('description', models.CharField(help_text='Descripción de la comida', max_length=255, verbose_name='Descripción')),
                ('ingredients', models.JSONField(help_text='Dict con ingredientes y cantidades en kg', verbose_name='Ingredientes')),
                ('total_co2', models.FloatField(help_text='Emisiones totales calculadas en kg de CO2', validators=[django.core.validators.MinValueValidator(0)], verbose_name='CO2 Total (kg)')),
                ('meal_date', models.DateField(verbose_name='Fecha de la comida')),
                ('is_vegetarian', models.BooleanField(default=False, verbose_name='Vegetariana')),
                ('is_vegan', models.BooleanField(default=False, verbose_name='Vegana')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Comida',
                'verbose_name_plural': 'Comidas',
                'ordering': ['-meal_date', '-created_at'],
                'indexes': [models.Index(fields=['user', '-meal_date'], name='meals_m_mea_user_id_df04b6_idx')],
            },
        ),
    ]
