# Generated by Django 5.2.7 on 2025-11-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcoTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp automático de creación', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp automático de última modificación', verbose_name='Última actualización')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('category', models.CharField(choices=[('meals', 'Comidas'), ('transport', 'Transporte'), ('energy', 'Energía'), ('water', 'Agua'), ('waste', 'Residuos'), ('general', 'General')], default='general', max_length=20, verbose_name='Categoría')),
                ('icon', models.CharField(default='leaf', help_text='Nombre del icono de lucide-react', max_length=50, verbose_name='Icono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Eco Tip',
                'verbose_name_plural': 'Eco Tips',
                'db_table': 'eco_tips',
                'ordering': ['category', 'title'],
            },
        ),
    ]
